### ISSUE TITLE
Help installint

### ISSUE THREAD

**Issue by oasec1** [jbc22/hipara#1]
I followed the procedures you identified and when I ran the command from the complied folder i get this error. I have disabled my AV. Any idea as to what could cause this?

C:\hipara\compiled>fltmc load scanner

Load failed with error: 0x800704fb
This driver has been blocked from loading

**Comment by jbc22** [comment]
Seems like this is caused on 64-bit OSes because the driver is not currently signed with a proper authority. We are currently working to get it properly signed. Are you running a 64-bit OS? Let me know either way and thanks for reporting this!

**Comment by oasec1** [comment]
Yes 2008 R2 server X64. 

Thanks,
Robert

**Comment by jbc22** [comment]
Awesome! I am working with GoDaddy to get a signing cert. In the mean time,
turning off code-signing is another alternative. I'd suggest this *only* for
testing. It can be done when rebooting into Safe Mode, it's one of the
options. Thanks for the interest and feedback, Rob!

**Comment by oasec1** [comment]
Thanks for the program I see a lot of use for  it

**Comment by jbc22** [comment]
@oasec1 - can I ask that you try the latest version? It is an MSI installer and I have signed the binary so you should not receive that error. Please email me at to my gmail account if you are interested: brettcu.

**Comment by oasec1** [comment]
Sure I can try to install the latest version tomorrow and let you know how
it goes

**Comment by jbc22** [comment]
Please email me: brettcu@gmail.com

**Comment by jbc22** [comment]
Released a signed-driver with DigitCert, sha2 high assurance. The latest client can be found https://www.hipara.org/files/hipara.zip
